export enum AuthActionTypes {
    CREATE_ACCOUNT = "CREATE_ACCOUNT",
    DEACTIVATE_ACCOUNT = "DEACTIVATE_ACCOUNT",
    DELETE_ACCOUNT = "DELETE_ACCOUNT",
    FETCH_USER = "FETCH_USER",
    RESET_PASSWORD = "RESET_PASSWORD",
    REQUEST_PASSWORD_RESET = "REQUEST_PASSWORD_RESET",
    SIGN_IN = "SIGN_IN",
    SIGN_OUT = "SIGN_OUT",
    UPDATE_EMAIL = "UPDATE_EMAIL",
    UPDATE_PASSWORD = "UPDATE_PASSWORD",
}

export enum NavActionTypes {
    CLEAR_BANNER_TEXT = "CLEAR_BANNER_TEXT",
    SET_BANNER_TEXT = "SET_BANNER_TEXT"
}